### PR TITLE
tinygo support, goroutine hack change, fix panic for invalid stderr, add test

### LINKED ISSUE #65: In wasm os.StdErr is invalid
Not sure what we can do though without any log but... at least it shouldn't panic

panic: runtime error: invalid memory address or nil pointer dereference

console_logging.go:98 +0x4

### PR DESCRIPTION
**Pull request by ldemailly**
Fixes #65

For tinygo (once debug.Buildinfo is fixed in https://github.com/tinygo-org/tinygo/pull/4343) the issue was the linkname hacks that work for go do not exist, but there is instead a `internal/task.Current` that we use but convert to an id because... folks aren't convinced we need an id (even though we do...)

Also switched to letting https://github.com/kortschak/goroutine deal with maintaining the hack (adds a dependency but... oh well)

### CODE REVIEW

File: goroutine/gid_test.go [hunk 1]
```diff
@@ -19,8 +19,12 @@ func TestID(t *testing.T) {
 	if got != want {
 		t.Fatalf("unexpected id for main goroutine: got:%d want:%d", got, want)
 	}
+	n := 1000000 // for regular go
+	if IsTinyGo {
+		n = 1000 // for tinygo
+	}
```
Comment (ccoVeille) [inline goroutine/gid_test.go:25]: This comment could be improved.

It explains what you are doing, but not why you are using a lower value for tinygo

File: goroutine/gid_test.go [hunk 2]
```diff
@@ -35,8 +39,15 @@ func TestID(t *testing.T) {
...
 
+var testID int64
+
 // goid returns the goroutine ID extracted from a stack trace.
 func goid() int64 {
+	if IsTinyGo {
+		// pretty horrible test that aligns with the implementation, but at least it tests we get 1,2,3... different numbers.
+		testID++
+		return testID
+	}
```
Comment (ccoVeille) [inline goroutine/gid_test.go:50]: Shouldn't use atomic.Int64 ?

File: goroutine/gid_test.go [hunk 3]
```diff
@@ -47,8 +58,9 @@ func goid() int64 {
 	return id
 }
 
+var gotid int64
+
 func BenchmarkGID(b *testing.B) {
-	var gotid int64
```
Comment (ccoVeille) [inline goroutine/gid_test.go:51]: I don't understand this change

File: goroutine/gid_tinygo.go [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+	task := uintptr(currentTask())
+	lock.Lock()
+	if id, ok := mapping[task]; ok {
+		lock.Unlock()
+		return id
+	}
+	counter++
+	mapping[task] = counter
+	lock.Unlock()
+	return counter
```
Comment (ccoVeille) [inline goroutine/gid_tinygo.go:31]:
```suggestion
func ID() int64 {
	task := uintptr(currentTask())
	lock.Lock()
	defer lock.Unlock()
	if id, ok := mapping[task]; ok {
		return id
	}
	counter++
	mapping[task] = counter
	return counter
```

File: goroutine/gid_tinygo.go [hunk 5]
```diff
@@ -0,0 +1,37 @@
...
+	// or, super fast but ugly large numbers/pointers:
+	//return int64(uintptr(currentTask()))
```
Comment (ccoVeille) [inline goroutine/gid_tinygo.go:33]: Do you need to keep this?

```suggestion
```

File: console_logging.go [hunk 6]
```diff
@@ -88,13 +88,24 @@ var (
 	Color = false
 )
 
+func IsValid(file *os.File) bool {
+	if file == nil {
+		return false
+	}
+	_, err := file.Stat()
+	return err == nil
```
Comment (ccoVeille) [inline console_logging.go:96]: Don't you need to check more than that?

Such as the file is not a directory or a special file, or is readable

File: console_logging.go [hunk 7]
```diff
@@ -88,13 +88,24 @@ var (
 	Color = false
 )
 
+func IsValid(file *os.File) bool {
```
Comment (ccoVeille) [inline console_logging.go:91]: Please add a comment, but also rename to something meaningful

Maybe


```suggestion
func IsValidFile(file *os.File) bool {
```

File: goroutine/gid_tinygo.go (hunk 4 above)
Comment (ccoVeille) [inline goroutine/gid_tinygo.go:31]: Is there nothing in atomic std lib for that?

File: console_logging.go (hunk 7 above)
Comment (ccoVeille) [inline console_logging.go:91]: I don't think you are using this method in your PR

Fo you need it?

File: goroutine/gid_test.go (hunk 1 above)
Comment (ldemailly) [reply goroutine/gid_test.go:25]: tinygo OOMs but yes let me put that in

File: goroutine/gid_test.go (hunk 2 above)
Comment (ldemailly) [reply goroutine/gid_test.go:50]: for the same reason there is a mutex even though it's not needed, possibly, yet this is test code that we know is actually not run in parallel

File: goroutine/gid_test.go (hunk 3 above)
Comment (ldemailly) [reply goroutine/gid_test.go:51]: it gets optimized to 0ns otherwise with tiny go when not doing the map

File: goroutine/gid_tinygo.go (hunk 4 above)
Comment (ldemailly) [reply goroutine/gid_tinygo.go:31]: I don't like defer when the code is a few lines and the exit points are clear
in theory I could for instance log the value after the unlock and minimize the critical section

admittedly there is nothing outside of the critical section but the return itself and the defer version is one less line so... could be fine

I also considered that in tinygo maybe defer is more expensive for the compiler to implement than explicit

adding a comment

File: goroutine/gid_tinygo.go (hunk 5 above)
Comment (ldemailly) [reply goroutine/gid_tinygo.go:33]: yes because it's an option (and also what I use to benchmark)

File: console_logging.go (hunk 6 above)
Comment (ldemailly) [reply console_logging.go:96]: This check is about not panicking/failing when os.StdErr doesn't exist (wasm case, or it's been .Close()ed) - it's to avoid the color mode in init failing

File: console_logging.go (hunk 7 above)
Comment (ldemailly) [reply console_logging.go:91]: I probably should make it `isValid` just figured it may be useful but yes if I leave it exposed, it should have a doc

File: goroutine/gid_tinygo.go (hunk 4 above)
Comment (ldemailly) [reply goroutine/gid_tinygo.go:31]: there is sync.Map but I don't think that'd be better

File: console_logging.go (hunk 7 above)
Comment (ldemailly) [reply console_logging.go:91]: it's used here: https://github.com/fortio/log/pull/66/files#diff-ff87b7c4777a35588053a509583d66c9f404ccbea9e1c71d2a5f224d7ad1323eR177

Comment (ldemailly) [reply console_logging.go]: made private but also added comment

File: goroutine/gid_test.go (hunk 2 above)
Comment (ldemailly) [reply goroutine/gid_test.go]: did

File: console_logging.go (hunk 7 above)
Comment (ccoVeille) [reply console_logging.go]: Indeed

File: goroutine/gid_tinygo.go (hunk 5 above)
Comment (ldemailly) [reply goroutine/gid_tinygo.go:33]: I know the mantra, it's in git, don't keep commented out code, delete them btw... just happens to not always agree :)

File: goroutine/gid_test.go [hunk 8]
```diff
@@ -35,8 +40,14 @@ func TestID(t *testing.T) {
 	wg.Wait()
 }
 
+var testID int64
+
 // goid returns the goroutine ID extracted from a stack trace.
 func goid() int64 {
+	if IsTinyGo {
+		// pretty horrible test that aligns with the implementation, but at least it tests we get 1,2,3... different numbers.
+		return atomic.AddInt64(&testID, 1)
```
Comment (ccoVeille) [inline goroutine/gid_test.go:49]: This is the old way to use atomic

Now you could/should use `var testID atomic.Int64`

Then here you can use


```suggestion
		return testID.Add(1)
```

More information here
https://pkg.go.dev/sync/atomic#Int64

Comment (ldemailly) [reply goroutine/gid_test.go:49]: I'm not going to pretend I knew and did it on purpose, yet

https://github.com/fortio/log/blob/main/go.mod#L3

vs

Screenshot 2024-07-17 at 12 03 49 PM

Comment (ccoVeille) [reply goroutine/gid_test.go:49]: Haha

File: console_logging.go [hunk 9]
```diff
@@ -88,13 +88,26 @@ var (
...
+func isValid(file *os.File) bool {
+	if file == nil {
+		return false
+	}
+	_, err := file.Stat()
+	return err == nil
+}
+
 // ConsoleLogging is a utility to check if the current logger output is a console (terminal).
 func ConsoleLogging() bool {
```
[the remark this answers is not in the document]
Comment (ldemailly) [reply console_logging.go:102]: go isn't big on `Has`/`Is` (as in a bool return implies Is/Has) - also it's published that way so while
IsTerminal would maybe be a better name, not going to change it, I should/could add a comment probably but that's not exactly related to this PR's changes (even if it's where it failed)

File: logger_test.go [hunk 10]
```diff
@@ -930,6 +930,17 @@ func TestConfigFromEnvOk(t *testing.T) {
 	}
 }
 
+func TestInvalidFile(t *testing.T) {
+	prev := jWriter.w
+	invalidFile := os.NewFile(^uintptr(0), "invalid-file")
```
[the remark this answers is not in the document]
Comment (ldemailly) [reply logger_test.go:935]: it is (bit operation), it turns 0 into 0xffffffffffffffff which is unlikely to be a valid FD

File: logger_test.go [hunk 11]
```diff
@@ -930,6 +930,17 @@ func TestConfigFromEnvOk(t *testing.T) {
...
+	jWriter.w = invalidFile
+	b := ConsoleLogging()
```
[the remark this answers is not in the document]
Comment (ldemailly) [reply logger_test.go:937]: sure, it's also a test, and a boolean variable used 2 lines below

File: logger_test.go [hunk 12]
```diff
@@ -930,6 +930,17 @@ func TestConfigFromEnvOk(t *testing.T) {
...
+	jWriter.w = prev
+	if b {
+		t.Errorf("expected not to be console logging")
+	}
+}
+
 // io.Discard but specially known to by logger optimizations for instance.
```
Comment (ldemailly) [inline logger_test.go:944]:
```suggestion
// like io.Discard except io.Discard is checked for by logger optimizations and we want to avoid that.
```

[the remark this answers is not in the document]
Comment (ldemailly) [reply logger_test.go]: see commit

Comment (ccoVeille) [reply logger_test.go]: Clearer, but I still don't get the "checked for by logger"

for + by look awkward

Comment (ldemailly) [reply logger_test.go]: https://cs.opensource.google/go/go/+/refs/tags/go1.22.5:src/log/log.go;l=84

File: logger_test.go [hunk 13]
```diff
@@ -930,7 +930,18 @@ func TestConfigFromEnvOk(t *testing.T) {
...
+	invalidFile := os.NewFile(^uintptr(0), "invalid-file")
+	jWriter.w = invalidFile
+	b := ConsoleLogging()
+	jWriter.w = prev
+	if b {
+		t.Errorf("expected not to be console logging")
+	}
+}
+
+// like io.Discard except io.Discard is checked for by logger optimizations and we want to avoid that.
```
Comment (ldemailly) [inline logger_test.go:944]:
```suggestion
// like io.Discard except io.Discard is checked for by logger optimizations and we want to avoid that.
// e.g. https://cs.opensource.google/go/go/+/refs/tags/go1.22.5:src/log/log.go;l=84
```

File: logger_test.go (hunk 12 above)
Comment (ldemailly) [reply logger_test.go]: added ^ to the comment

File: goroutine/gid_tinygo.go [hunk 14]
```diff
@@ -0,0 +1,37 @@
...
+}
+
+//go:linkname currentTask internal/task.Current
```
Comment (ccoVeille) [inline goroutine/gid_tinygo.go:36]: I don't think I ever face this directive

Can you explain?

This comment is non blocking of course

File: logger_test.go [hunk 15]
```diff
@@ -930,7 +930,22 @@ func TestConfigFromEnvOk(t *testing.T) {
...
```
Comment (ccoVeille) [inline logger_test.go:947]:
```suggestion
// like io.Discard, except io.Discard is checked for, by logger optimizations, and we want to avoid that.
```

Maybe the commas will make the sentence looks valid

File: goroutine/gid_tinygo.go (hunk 5 above)
Comment (ccoVeille) [reply goroutine/gid_tinygo.go:33]: You didn't reply about this one

@ldemailly

File: goroutine/gid_tinygo.go [hunk 16]
```diff
@@ -0,0 +1,37 @@
...
+	"sync"
+	"unsafe"
+)
+
+const IsTinyGo = true
+
+var (
+	counter int64
+	mapping = make(map[uintptr]int64)
+	// TinyGo at the moment is single threaded so this is not needed but it's good to have anyway
```
Comment (ccoVeille) [inline goroutine/gid_tinygo.go:15]:
```suggestion
	// TinyGo at the moment is single threaded, so this is not needed, but it's good to have anyway
```

File: goroutine/gid_tinygo.go [hunk 17]
```diff
@@ -0,0 +1,37 @@
...
+	// in case that changes. It does had ~5ns (from 20ns vs 4ns big go) but it's better to be correct.
```
Comment (ccoVeille) [inline goroutine/gid_tinygo.go:16]:
```suggestion
	// in case that changes. It does had ~5ns (from 20ns vs 4ns big go), but it's better to be correct.
```

Comment (ccoVeille) [inline goroutine/gid_tinygo.go:16]:
```suggestion
	// in case that changes. It does add ~5ns (from 20ns vs 4ns big go) but it's better to be correct.
```

`does had` is grammatically wrong, I think it's `add`

File: goroutine/gid_tinygo.go [hunk 18]
```diff
@@ -0,0 +1,37 @@
...
+	// In theory the mutex could be noop on platforms where everything is single threaded.
```
Comment (ccoVeille) [inline goroutine/gid_tinygo.go:17]:
```suggestion
	// In theory, the mutex could be noop on platforms where everything is single threaded.
```

File: logger.go [hunk 19]
```diff
@@ -174,6 +174,9 @@ func (l *JSONEntry) Time() time.Time {
 
 //nolint:gochecknoinits // needed
 func init() {
+	if !isValid(os.Stderr) { // wasm in browser case for instance
+		SetOutput(os.Stdout) // this could also be invalid too but... we tried.
```
Comment (ccoVeille) [inline logger.go:178]:
```suggestion
		SetOutput(os.Stdout) // this could also be invalid too, but... we tried.
```

File: goroutine/gid_tinygo.go (hunk 14 above)
Comment (ldemailly) [reply goroutine/gid_tinygo.go:36]: it means create the function `currentTask` here but when it's called, call `internal/task.Current` instead

in this case (tinygo)

https://github.com/tinygo-org/tinygo/blob/v0.32.0/src/internal/task/task_stack.go#L39

which being internal... isn't otherwise reachable

go folks are trying to get the cat back in the bag in https://github.com/golang/go/issues/67401

File: goroutine/gid_tinygo.go (hunk 17 above)
Comment (ldemailly) [reply goroutine/gid_tinygo.go:16]: "add" not "had" btw :) a bit more important than the comas :)

File: logger_test.go (hunk 15 above)
Comment (ldemailly) [reply logger_test.go]: tried something else ptal

**Review by ccoVeille — APPROVED** [review]

**Comment by ldemailly** [comment]
So I got it to link even though I have yet to get it to run with tinygo

See
https://github.com/dispatchrun/net/issues/37
https://github.com/tinygo-org/tinygo/pull/4345
https://github.com/tinygo-org/tinygo/issues/4346

but once these merge/are resolved, this will be tinygo compatible


ps: because tinygo doesn't have stack traces the file name/line number tests do fail but it's ok
